import type { CollectionConfig } from 'payload'

import { authenticated } from '../access/authenticated'

export const Leads: CollectionConfig = {
  slug: 'leads',
  admin: {
    useAsTitle: 'email',
    defaultColumns: ['email', 'requestKind', 'lifecycleStage', 'status', 'locale', 'createdAt'],
    group: 'Marketing',
  },
  access: {
    create: () => false,
    read: authenticated,
    update: authenticated,
    delete: authenticated,
  },
  fields: [
    { name: 'submissionId', type: 'text', required: true, unique: true, index: true, admin: { readOnly: true } },
    { name: 'email', type: 'email', required: true, index: true },
    {
      name: 'kind',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Newsletter subscriber (legacy; use Subscribers)', value: 'newsletter' },
        { label: 'Contact request', value: 'contact' },
      ],
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'new',
      index: true,
      options: [
        { label: 'New', value: 'new' },
        { label: 'Contacted', value: 'contacted' },
        { label: 'Subscribed', value: 'subscribed' },
        { label: 'Unsubscribed', value: 'unsubscribed' },
      ],
    },
    { name: 'firstName', type: 'text' },
    { name: 'lastName', type: 'text' },
    { name: 'phone', type: 'text' },
    { name: 'message', type: 'textarea' },
    { name: 'service', type: 'text' },
    {
      name: 'requestKind',
      type: 'select',
      required: true,
      defaultValue: 'general',
      index: true,
      options: [
        { label: 'General', value: 'general' },
        { label: 'Training', value: 'training' },
        { label: 'Yacht charter', value: 'charter' },
        { label: 'Yacht delivery', value: 'delivery' },
        { label: 'Yacht expertise', value: 'expertise' },
      ],
    },
    {
      name: 'lifecycleStage',
      type: 'select',
      required: true,
      defaultValue: 'inquiry',
      index: true,
      options: [
        { label: 'Inquiry', value: 'inquiry' },
        { label: 'Triaged', value: 'triaged' },
        { label: 'Qualified', value: 'qualified' },
        { label: 'Unqualified', value: 'unqualified' },
        { label: 'Won', value: 'won' },
        { label: 'Lost', value: 'lost' },
        { label: 'Expired', value: 'expired' },
      ],
    },
    {
      name: 'qualificationStatus',
      type: 'select',
      required: true,
      defaultValue: 'unknown',
      options: [
        { label: 'Unknown', value: 'unknown' },
        { label: 'Potential', value: 'potential' },
        { label: 'Qualified', value: 'qualified' },
        { label: 'Unqualified', value: 'unqualified' },
      ],
    },
    {
      name: 'sourceChannel',
      type: 'select',
      required: true,
      defaultValue: 'unknown',
      index: true,
      options: [
        { label: 'Organic', value: 'organic' },
        { label: 'Direct', value: 'direct' },
        { label: 'Referral', value: 'referral' },
        { label: 'Paid', value: 'paid' },
        { label: 'Unknown', value: 'unknown' },
      ],
    },
    { name: 'requestedStartDate', type: 'date' },
    { name: 'requestedEndDate', type: 'date' },
    { name: 'requestedLocation', type: 'text' },
    { name: 'partySize', type: 'number', min: 1, max: 48 },
    { name: 'yachtReference', type: 'text' },
    {
      name: 'requestContext',
      type: 'json',
      admin: { readOnly: true, description: 'Sanitized form context. Never exposed to the SEO agent.' },
    },
    { name: 'triagedAt', type: 'date' },
    { name: 'qualifiedAt', type: 'date' },
    { name: 'closedAt', type: 'date' },
    { name: 'lossReason', type: 'text' },
    { name: 'locale', type: 'text' },
    { name: 'sourceUrl', type: 'text' },
    { name: 'utm', type: 'text' },
    { name: 'ip', type: 'text', admin: { readOnly: true } },
    { name: 'userAgent', type: 'textarea', admin: { readOnly: true } },
    { name: 'consentAt', type: 'date', required: true },
  ],
  timestamps: true,
}
